// Describes the shape of a task object throughout the app.
// Every field here mirrors a column in the Supabase tasks table.
// Optional fields (?) may be undefined if the user didn't fill them in.
export interface Task {
    id: string                                          // UUID generated by Supabase
    title: string                                       // required — the task name
    description?: string                               // optional — extra detail
    status: 'todo' | 'in_progress' | 'in_review' | 'done' // which column the task lives in
    priority: 'low' | 'normal' | 'high'                // controls badge color on the card
    label?: string                                      // optional — a custom tag like "Bug" or "Feature"
    due_date?: string                                   // optional — stored as an ISO date string (YYYY-MM-DD)
    user_id: string                                     // ties the task to the guest user via Supabase Auth
    created_at: string                                  // auto-set by Supabase on insert
}